/**
 * @file tcp-serv.cpp
 * @author Andrii Klymenko
 * @brief Implementation of the TCP version of pseudo-server of IPK25CHAT protocol for project's testing
 * Almost fully generated by AI
 */

#include <stdio.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h> // read(), write(), close()
#include <arpa/inet.h> // inet_addr()
#include <errno.h>

#define MAX 89000
#define PORT 8080
#define SA struct sockaddr

// Function to handle sending and receiving messages
void func(int connfd)
{
    char buff[MAX];
    int n;
    int choice;

    // Infinite loop for chat
    for (;;) {
        // Display menu
        printf("\nChoose an option:\n");
        printf("1. Send a message to the client\n");
        printf("2. Receive a message from the client\n");
        printf("3. Exit\n");
        printf("Enter your choice: ");
        scanf("%d", &choice);
        getchar(); // Consume the newline character left by scanf

        switch (choice) {
            case 1: // Send a message to the client
                bzero(buff, MAX);
                printf("Enter the message to send: ");
                n = 0;
                char c;
                while ((c = getchar()) != '\n') buff[n++] = c;
                buff[n++] = '\r';
                buff[n++] = '\n';
                write(connfd, buff, strlen(buff));
                printf("Message sent to client: %s", buff);
                break;

            case 2: // Receive a message from the client
                bzero(buff, MAX);
                read(connfd, buff, sizeof(buff));
                printf("Message from client: %s", buff);
                break;

            case 3: // Exit
                printf("Server Exit...\n");
                write(connfd, "exit", 4); // Notify the client to exit
                return;

            default:
                printf("Invalid choice! Please try again.\n");
                break;
        }
    }
}

// Driver function
int main()
{
    int sockfd, connfd, len;
    struct sockaddr_in servaddr, cli;

    // Socket creation and verification
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd == -1) {
        printf("Socket creation failed...\n");
        exit(0);
    }
    else
        printf("Socket successfully created..\n");

    int enable = 1;
    setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR,
    &enable, sizeof(enable));

    bzero(&servaddr, sizeof(servaddr));

    // Assign IP, PORT
    servaddr.sin_family = AF_INET;
    servaddr.sin_addr.s_addr = inet_addr("127.0.0.1");
    servaddr.sin_port = htons(PORT);

    // Binding newly created socket to given IP and verification
    if ((bind(sockfd, (SA*)&servaddr, sizeof(servaddr))) != 0) {
        printf("Socket bind failed... errno = %d\n", errno);
        exit(0);
    }
    else
        printf("Socket successfully binded..\n");

    // Now server is ready to listen and verification
    if ((listen(sockfd, 5)) != 0) {
        printf("Listen failed...\n");
        exit(0);
    }
    else
        printf("Server listening..\n");
    len = sizeof(cli);

    // Accept the data packet from client and verification
    connfd = accept(sockfd, (SA*)&cli, &len);
    if (connfd < 0) {
        printf("Server accept failed...\n");
        exit(0);
    }
    else
        printf("Server accepted the client...\n");

    // Function for chatting between client and server
    func(connfd);

    // After chatting, close the socket
    close(sockfd);
    return 0;
}
